import type { Metadata } from "next";
import "./globals.css";
import RecoilProvider from "./ClientProviders";
import { AntdRegistry } from "@ant-design/nextjs-registry";
export const metadata: Metadata = {
  title: "POTECH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </head>
      <body>
        <AntdRegistry>
          <RecoilProvider>
            {children}
          </RecoilProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
